### ISSUE TITLE
Please support GHC 8.8

### ISSUE THREAD

**Issue by gwils** [GaloisInc/json#11]
The repo does not currently build with 8.8. Please release a new version with support.
I notice there is a pull request at #10

**Comment by simonmichael** [comment]
Ping, it would be great if #10 could be merged and a base 4.13 compatible release could be made soon. This will allow yesod-based apps like hledger-web to be built with ghc 8.8 and to be included in the next Stackage LTS and the distro packaging systems which depend on that.

**Comment by simonmichael** [comment]
Or maybe #10 is redundant, since I see https://github.com/GaloisInc/json/commit/9d36ca5d

**Comment by simonmichael** [comment]
I confirm that current json master builds with GHC 8.8.1, with one warning:
```
json> /private/var/folders/r7/f9j9c2zd1k97v47cr84j_qvc0000gn/T/stack73335/json-0.9.3/Text/JSON/String.hs:39:1: warning: [-Wunused-imports]
json>     The import of ‘Control.Applicative’ is redundant
json>       except perhaps to import instances from ‘Control.Applicative’
json>     To import instances alone, use: import Control.Applicative()
json>    |
json> 39 | import Control.Applicative((<$>))
json>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
and seems to work.

**Comment by simonmichael** [comment]
Hi, you didn't mention why this was closed 12 hours ago... hopefully it means a release is coming.

**Comment by simonmichael** [comment]
Hi @gwils, I guess you're the original reporter of this issue. Why did you close it ?

**Comment by simonmichael** [comment]
Ah.. I just realised that json is a legacy library that I had a stray dependency on it. Thanks, disregard.
